---
abstract: "Very simple properties/attributes/fields for Perl\r"
author:
  - 'John Scoles <byterock@hotmail.com>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Orignal
no_index:
  directory:
    - t
    - inc
resources:
  repository: git://github.com/byterock/Orignal.git
version: 0.03
